### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by zitoune000** [plaidpants/soundstagevr#37] opened 2021-03-16 06:25 UTC
Hello,
Im player on pc vr and im follower of soundstage since the beginning.
Do you think a multiplayer mode will ne possible?

**Comment by plaidpants** [comment] 2021-03-19 20:54
It should be possible but may require quite a bit of work, promising work was done for Tilt Brush but the multiplayer code for that port has not been released.

**Comment by plaidpants** [comment] 2021-03-19 20:55
duplicate of issue #18

**Closed as completed** 2021-03-19 20:55 UTC
Labels: duplicate
